# Generated by Django 3.2 on 2021-04-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmfood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealtoorder',
            name='mealid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='crmfood_app.meal'),
        ),
        migrations.AddField(
            model_name='mealtoorder',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crmfood_app.order'),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmfood_app.department'),
        ),
        migrations.AddField(
            model_name='meal',
            name='categoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmfood_app.mealcategory'),
        ),
        migrations.AddField(
            model_name='check',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crmfood_app.order'),
        ),
    ]
